-- ============================================================
-- GasPrice — Schema PostgreSQL (Supabase)
-- ============================================================
-- Execute este arquivo no SQL Editor do seu projeto Supabase:
--   https://supabase.com/dashboard -> seu projeto -> SQL Editor
--
-- Depois de criar as tabelas, execute também o "supabase_seed.sql"
-- para popular com os dados iniciais.
-- ============================================================

-- Postos de combustível
create table if not exists public.postos (
    id bigint generated by default as identity primary key,
    nome text not null,
    bandeira text not null default 'Bandeira Branca',
    cidade text not null,
    endereco text not null default '',
    bairro text not null default '',
    latitude double precision,
    longitude double precision,
    created_at timestamptz not null default now()
);

-- Preços por combustível (um posto pode ter vários combustíveis)
create table if not exists public.precos (
    id bigint generated by default as identity primary key,
    posto_id bigint not null references public.postos (id) on delete cascade,
    tipo_combustivel text not null,
    preco double precision not null check (preco > 0),
    data_atualizacao timestamptz not null default now()
);

create index if not exists idx_precos_posto_id on public.precos (posto_id);
create index if not exists idx_precos_combustivel on public.precos (tipo_combustivel);

-- ============================================================
-- Row Level Security
-- A Service Role Key usada pelo backend ignora estas políticas.
-- As políticas abaixo permitem que a ANON KEY (frontend público)
-- também consiga ler e cadastrar preços.
-- ============================================================
alter table public.postos enable row level security;
alter table public.precos enable row level security;

create policy "postos_read_public" on public.postos for select using (true);
create policy "postos_insert_public" on public.postos for insert with check (true);
create policy "precos_read_public" on public.precos for select using (true);
create policy "precos_insert_public" on public.precos for insert with check (true);
create policy "precos_update_public" on public.precos for update using (true) with check (true);
